Makefile
tox.ini

This pull request contains the changes described in issue #16

Fixes for ld issue #16: Test related issues in tox.ini and Makefile

---

ld/__init__.py

This merge request contains the fixes for issues #21 and #22 (... this time without screwing up ;-)
Please review and merge.

Fixes for issues #21 and #22.

---

ld/__init__.py

This merge request fixes issue #26.
Please review and merge.

Fix for issue #26: Exception when lsb_release returns no LSB info

---

ld/__init__.py
tests/resources/special/lsb_release.ubuntu14.nomodules.out
tests/resources/special/lsb_release.ubuntu14.trailingblanks.out
tests/test_ld.py

This merge request adds some test cases for lsb_release that increase the test coverage and test some more corner cases.

Fix for issue #38: Added test cases for lsb_release to increase test coverage.

---

ld/__init__.py

This PR addresses the new issue #42.
Please review and merge, if you agree.

Fix for issue #42: Optimization: __init__() work only partially used.

---

ld/__init__.py

This PR fixes issue #44.
Please review and merge, if you agree.

Fix for issue #44: Inconsistency: dist_* vs. distro_* in public interface.

---

ld/__init__.py
tests/test_ld.py

Fixes #58: Added global functions get_*_release_attr(), and test code for them

---

README.md
README.rst
setup.py

Details:
* Changed version back to 0.5.0dev to make it clear that its is not yet released.
* Switched Pypi to use README.md to avoid double maintenance, and removed README.rst.

Prep for 0.5.0 release

---

tests/resources/distros/exherbo/etc/os-release
tests/test_ld.py

... based on input from Philantrop. Thanks!

Fixes #76: Added data to the testcases for Exherbo

---

setup.py

This PR bumps the version to 0.5.0 and once merged, will trigger a release to Pypi and an update of the documentation on RTD.
I'll keep this PR open for a week, for people to review and comment.
Here is the API documentation for this version: https://ld.readthedocs.org/en/latest/

Ready to release v0.5.0.

---

README.md

In addition, changed links of PyPI buttons to target ld on PyPI.

Updated README.md to show installation of v0.5.0 from GitHub.

---

docs/index.rst
ld/__init__.py
tests/test_ld.py

Please review.
See discussion in issue #80.

Fixes #80, fixes #96: Removed mentioning of unknown "nexus_centos" distro.

---

README.md

Updated README.md file (for GitHub) for v0.5.0 being released.

---

.travis.yml

This is an attempt to get this added. Let's see if it works.

Fixes #55: Add Python 3.4 to Travis control file.

---

docs/index.rst
ld.py

Ready for merge - please review.
Details:
* Removed todo2 about issue #95 (that was closed).
* Removed erroneous parenthesis in title.
* Made reference for more details consistent, for the module-global `*_release_info()` functions.

Minor doc updates

---

Makefile
README.md
README.rst
distro.py
docs/compatibility.rst
docs/conf.py
docs/index.rst
query_local_distro.py
setup.py
tests/test_ld.py
tox.ini

Changes the name from `ld` to `distro`, pending @MartijnBraam.

changed name to distro

---

README.md
README.rst

Ready for merge. Please review.
Details:
- Updated the GitHub readme file to replace the list of tested distros with a link to the test directory which shows them, in order to save the maintenance effort and to provide automatic accuracy.
- Updated the PyPI readme file to let the link to the GitHub repo target the readme section instead of the top of the page.

Minor updates to the readme files.

---

tests/resources/distros/scientific6/etc/redhat-release
tests/resources/distros/scientific6/etc/system-release
tests/resources/distros/scientific7/etc/os-release
tests/resources/distros/scientific7/etc/redhat-release
tests/resources/distros/scientific7/etc/sl-release
tests/resources/distros/scientific7/etc/system-release
tests/test_distro.py

add scientific linux testcase

---

tests/resources/distros/gentoo/etc/gentoo-release
tests/resources/distros/gentoo/etc/os-release
tests/test_distro.py

add gentoo testcase

---

CHANGES
MANIFEST.in

Include resources needed for tests and docs

---

.travis.yml

Seeing if this fixes our currently failing build on Travis

Explicitly set Python versions on Travis for flake

---

distro.py
tests/test_distro.py

Lazily load the LinuxDistribution data

---

CHANGELOG.md

Fix CHANGELOG.md issue links

---

distro.py

Small typo in the parameter docs

distro.py: include_name => include_uname in docs

---

.github/workflows/ci.yaml
setup.py
tox.ini

Python 3.9 was released Oct. 5, 2020.

Add testing and support for Python 3.9

---

.github/stale.yml

I've started using staling configs across many projects. I think it keeps things clean. It may be a tad controversial in such open projects, so I'd like to get opinions here.

Add stale.yml config

---

setup.py

It's not an official classifier :)

Remove MidnightBSD from classifiers

---

.pre-commit-config.yaml
dev-requirements.txt
tox.ini

Would be nice to save the trouble of having to run pylint on every push.

Add pre-commit config

---

CHANGELOG.md

Doh, forgot to update the release date for 1.6.0.

Fix release date for 1.6.0

---

.pre-commit-config.yaml

Bumps black to v22.3.0

---

tests/resources/distros/arch/usr/lib/os-release

This file was not updated since 2016. Something has changed in it.

Update archlinux resource for tests

---

src/distro/distro.py
tests/resources/distros/altlinux10/etc/altlinux-release
tests/resources/distros/altlinux10/etc/fedora-release
tests/resources/distros/altlinux10/etc/os-release
tests/resources/distros/altlinux10/etc/redhat-release
tests/resources/distros/altlinux10/etc/system-release
tests/test_distro.py

[ALT Linux](https://en.altlinux.org/Main_Page) is a set of operating systems based on RPM Package Manager (RPM) and built on a Linux kernel and Sisyphus package repository.

Add support for ALT Linux Server 10.1 distribution

---

.gitignore
.readthedocs.yaml
CHANGELOG.md
CONTRIBUTORS.md
Makefile
README.md
dev-requirements.txt
setup.cfg
src/distro/distro.py
tox.ini

Nothing too fancy. See commit messages.
btw, just noting that codecov doesn't work and that there are some discussions about this: https://github.com/codecov/codecov-action/issues/844
Also fixes #357

Optimize some repo metastuff and prepare v1.9.0
