- ld/__init__.py
- tests/test_ld.py
This merge request contains the implementation of the overall distro test, based on the new file structure under tests/resources.
In addition, it contains two fixes for issues that came up during the overall distro test:
1. `_attempt_to_get_release_file()` now returns the file path, instead of just the base file name. The prior code caused `distro_release_info()` to not find the file.
2. Not a real problem, but it helps when looking at an ldi object: Moved the determination of the distro file name using `_attempt_to_get_release_file()` into `__init__()`, so that the file that was found is stored in `self.distro_release_file`. In the prior code, the location of the file that was read was never stored anywhere in the ldi object, making debugging harder than needed. The `__init__()` method …
> Fix for issue #20: Overall distro test missing, part 2

- ld/__init__.py
- tests/test_ld.py
This PR completes issue #38, and brings the test coverage to 100%.
The added testcases revealed that `__repr__()` did not include the `self.dist` instance attribute, which gets created in a method. This was fixed as well.
Please review and merge, if you agree.
> Final fix for issue #38: Test coverage is below 100%

- tests/test_ld.py
The setup method for the overall distro test sets the PATH in the environment of the current Python process so that only the lsb_release command in the distro subtree is found. However, I verified that that PATH change remains in place across the whole test run.
This PR adds saving and restoring of the PATh value, in the setup and teardown routine of each testcase of the TestOverall class. This scopes the changed PATH to just the minimum, i.e. the testcases that need it.
Please review and merge, if you agree.
> Saving and restoring PATH in TestOverall

- ld/__init__.py
- ld/constants.py
- tests/resources/distros/ubuntu14/etc/debian_version
- tests/resources/testdistros/unknowndistro/etc/unknowndistro-release
- tests/test_ld.py
This PR contains fixes for issues #40 and #48, as proposed in the descriptions.
This includes some restructuring in the processing of distro release files.
Also, the distro release file dict now contains only those entries that were found (as opposed to all
entries with the empty string if no information was found). The users of accessor functions like `id()` or `get*attr()` see no change due to this, because they default non-existing entries to the empty string.
Finally, the distro ID found in the file name of the distro release file is no longer stored in `self.dist`, but as key 'id' in the distro release file dict. This seems to be more consistent, to me.
Note the change in expected test case results, when reviewing.
> Fixes for issues #40 and #48

- ld/__init__.py
- tests/test_ld.py
Please review.
This PR is largely independent of PR #51 (there is a trivial merge conflict, which I can resolve either way, whichever you pick first).
There are several things to watch out for when reviewing:
- It did not become a new `best_version()` method as suggested in a prior comment on the discussion of issue #29, but a new `best` parameter on the existing version related methods, that by default works as today, and that can be used to turn on the best precision algorithm. This is because there were five methods related to versions, and it did not seem appropriate to me to double their number.
- I first thought we need to add more sources for the version, i.e. the description fields of `os-release` and `lsb_release`, so I implemented support for them, by using their version if …
> Fixes #29: Version sometimes looses precision.

- ld/__init__.py
- query_local_distro.py
PR #51 added a hashbang to the `query_local_distro.py` script, but did it incorrectly (and apparently without any testing ... :-(
This PR fixes the hashbang.
I verified that no other Python script contains an incorrect hashbang.
> Query script hashbang

- Makefile
- ld/__init__.py
- ld/constants.py
- query_local_distro.py
- setup.py
- tests/test_ld.py
- tox.ini
The Apache license requires to include a boilerplate text into each source file, as stated at the end of the LICENSE file. This PR adds such a text to *.py, Makefile, tox.ini.
> Fixes #63: Added Apache license header to *.py, Makefile, tox.ini

- ld/__init__.py
- tests/resources/testdistros/lsb/lsb_rc001/bin/lsb_release
- tests/resources/testdistros/lsb/lsb_rc002/bin/lsb_release
- tests/resources/testdistros/lsb/lsb_rc126/bin/lsb_release
- tests/resources/testdistros/lsb/lsb_rc130/bin/lsb_release
- tests/resources/testdistros/lsb/lsb_rc255/bin/lsb_release
- tests/test_ld.py
This PR improves the implementation of `_get_lsb_release_info()` so that it raises `subprocess.CalledProcessError`, if the lsb_release command fails with a non-zero exit code other than 127 (command not found). Exit code 127 continues to be ignored, producing an empty data source for lsb_release.
Testcases have been added for lsb_release commands that fail with a few popular exit codes.
> Fixes #59: Improved handling of lsb_release execution errors.

- ld/__init__.py
This PR adds the distro "KVM for IBM z Systems" with the ID "ibmkvm" to the set of reliable distros. See https://www-03.ibm.com/systems/z/solutions/virtualization/kvm/ for details.
> Added ibmkvm to set of reliable distros

- README.rst
- setup.py
Fixed the following issues in the setup.py script:
* Added the 'classifiers' argument.
* Changed the value of the 'license' argument from license file name to the actual license name.
* The 'long_description' argument is used by Pypi to build the Pypi home page. Changed it from the content of the README.rst file to the content of the README.md file (which is also shown on the Github project page).
Also, bumped version to 0.5.0.
> Fixes #64: Fixed missing or incorrect information in setup script + bumped version to 0.5.0

- ld/__init__.py
- setup.py
- tests/resources/distros/fedora19/etc/fedora-release
- tests/resources/distros/fedora19/etc/issue
- tests/resources/distros/fedora19/etc/issue.net
- tests/resources/distros/fedora19/etc/os-release
- tests/resources/distros/fedora19/etc/redhat-release
- tests/resources/distros/fedora19/etc/system-release
- tests/resources/distros/fedora19/etc/system-release-cpe
- tests/test_ld.py
This PR adds a distro testcase for Fedora 19. Fedora 19 has two Unicode characters (ö, and the single quote U+2019) in its distro codename (Schrödinger's Cat).
This revealed that there were still some issues related to Unicode processing. This PR fixes them. Changed the lsb_release command output to be expected in UTF-8, and adjusted the code. Changed conditional processing dependent on the Python version to use common code from the "six" module. This of course introduced a dependency on the "six" module, which was added to the setup script via an `install_requires` parameter. 
Unrelated to this, the incorrect statement that the VERSION attribute of the os-release file is used for the version was corrected to say that VERSION_ID is used (see `version()`).
> Fixes #70: Added testcase for Fedora 19, and some fixes.

- README.md
- README.rst
- docs/compatibility.rst
- docs/index.rst
- ld/__init__.py
- ld/constants.py
From the commit message:
Details:
* Fine tuning of documentation.
* Moved stuff from `__init__.py` to `index.rst`.
* Completed missing information in `info()`.
* Created section for review items and linked back to bug tracker issues.
* Consolidated supported distros and Python versions into file `docs/compatibility.rst`, and included it in docs. Cannot be included in the `README.* files`, though.
* Added hint to open issues to reliable ID table.
> Improved documentation.

- docs/index.rst
- ld.py
Ready to be merged.
Please review.
See issue #62 for details.
> Fixes #62: Documented that codename() returns string as-is.

- docs/index.rst
- ld.py
- tests/test_ld.py
Ready to be merged.
Please review.
Details from the commit log:
- Added a `best` parameter to `info()`.
- Fixed implementation of `info()` by adding the missing `'codename'` item in its result.
- Improved test cases for `info()` by adding a generic all-distro test that compares the result of `info()` with the result of the specific consolidated accessor functions.
- Minor editorial improvements in documentation of `info()`.
- Removed todo3 about issue #94.
> Fixes #94, fixes #112: Improved and fixed info() function.

- appveyor.yml
- distro.py
- tests/test_distro.py
- tox.ini
* Added Appveyor testing to verify that importing distro fails on Windows.
* Now skipping all tests if not on Linux.
* Added ImportError Exception when importing from non-linux platforms.
> raise exception when importing on non-supported platforms

- distro.py
`bytes` was introduced in python2.6 to aid in porting to python3 by providing
a single name to refer to the "binary string" type.
> Use `bytes` invariantly.

- distro.py
This helps for non-US languages, which otherwise traceback.
Fixes #140
> decode output of lsb_release as utf-8

- distro.py
> Get UNIXCONFDIR from environment first, fallback to /etc fixes #149

- distro.py
Also happens to fix #162 :)
Instead of checking if the file exists just try and open it and if we can't open it (For whatever reason, if it's not there, no permissions, etc) then we return as if it wasn't there.
> Race condition in _parse_distro_release_file

- .travis.yml
- README.md
- docs/index.rst
- setup.py
- tox.ini
* Remove pyt2.6 in all testing environments.
* Remove implicit argparse installation for py2.6.
> Remove Official Python26 support

- .travis.yml
- README.md
- docs/index.rst
- setup.py
Python3.3 has been end of lifed.  The tests have begun failing due to upstreams dropping support as well (notably pytest).
Like [the dropping of 2.6](https://github.com/nir0s/distro/pull/195) this doesn't necessarily mean that distro won't work on 3.3 but rather that it won't be tested on it.
> Drop python3.3 support

- distro.py
Hello.
Errors are raised when `$LANG` is not utf-8 (ex. `LANG=ja_JP.EUCJP`).
This cause a bug in `pip`.
https://github.com/pypa/pip/issues/4917
Would you review it ?
> Stdout of shell should be decoded with sys.getfilesystemencoding()

- distro.py
In order to be able to use `distro` in cross-platform programs without duplicated import guards, `distro` shouldn't raise on `import`.
For what it's worth, after this patch `distro` acts _mostly_ in the same way as `platform.linux_distribution` on non-linux platforms:
```
>>> platform.linux_distribution()
('', '', '')
>>> distro.id(), distro.version(), distro.codename()
('', '', '')
```
> Don't raise ImportError on non-linux platforms

- README.rst
- setup.py
This should make https://pypi.org/project/distro much more useful.
You'll need setuptools 38.6.0+ and twine 1.11+ to release/upload this; see Dustin Ingram's blog:
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
> Use Markdown for long description in setup.py

- README.md
The old one uses a now removed system, the link 404s
> Update Fedora package link

- distro.py
- tests/resources/distros/oracle7/etc/oracle-release
- tests/resources/distros/oracle7/etc/os-release
- tests/test_distro.py
It seems Oracle ships an /etc/os-release which has an ID of 'ol'.  To
make sure it returns the id "oracle" as mentioned in the docs, match
this.  Update the testing.
---
I noticed this from the following change which was proposed to OpenStack's bindep : https://review.openstack.org/#/c/536355/
You can see some small testing pulling it from docker in http://paste.openstack.org/show/726682/.  I confirmed I got "oracle" back there too with this small change.
> Update Oracle matching

- distro.py
Fixes #229
I'm sorry, I don't understand how the test cases work well enough to see why the existing uname_info tests failed to pick up this problem otherwise I would have adapted them to test this case too.  I'm guessing that they test the _uname_info() method directly instead of testing the uname_info() method but I don't quite see where that would be happening.
> Return _uname_info from the uname_info() method

- distro.py
- tests/test_distro.py
CloudLinux 5 and 6 only have redhat-release (making them show up with and id of rhel).
> Fixed CloudLinux id discovery

- .travis.yml
- dev-requirements.txt
- distro.py
- tests/test_distro.py
This builds on https://github.com/nir0s/distro/pull/231 to get the nir0s/distro python2.6-support branch working on Python-2.6.
> Fix python2.6 support

- distro.py
- tests/test_distro.py
since `platform.linux_distribution()` returns tuple of str， we should compatible with the same behavior on both python2 and python3.
1. open() return string on both python2 and python3, just keep it.
2. stdout of Popen() return string on python2, and bytes on python3,
decode to string.
> Keep output as native string so we can compatible with python2 interface

- .travis.yml
- setup.py
- tests/test_distro.py
- tox.ini
Hello @nir0s,
I believe that it would be nice to have tests for actual and upcoming Python versions.
These changes also:
- declare support for Python 3.7 and 3.8 at `setup.py`
- remove Python 3.3 from `tox`'s `envlist`
- remove [deprecated](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) `sudo` option from `.travis.yml`
- fix typos
Best regards!
> Improve testing

- distro.py
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> Ignore /etc/plesk-release file while parsing distribution

- distro.py
See #239 
Unfortunately this doesn't resolve all cases mentioned in #239 (Oracle Linux 6.1 is still not recognized correctly) but it will fix Oracle Linux 4 and 5.
> Fix Oracle 4/5 lsb_release id and names

- distro.py
This PR fixes detection of RHEL 6 ComputeNode.
This bug was originally reported by @CreRecombinase in https://github.com/spack/spack/issues/15251 and fixed in Spack's vendored copy of `distro` in https://github.com/spack/spack/pull/15253
Let me know if you want me to add unit tests for this. https://github.com/spack/spack/issues/15251 has the output of `lsb_release -a` for the problematic nodes.
> Fix detection of RHEL 6 ComputeNode

- distro.py
Ignore file `/etc/iredmail-release` while detecting target OS distribution, it may cause Ansible incorrectly identify target OS distro or release version.
File /etc/iredmail-release is generated by iRedMail - a popular open source mail server solution: https://www.iredmail.org/
- See also: https://github.com/ansible/ansible/pull/72538
> Ignore file 'iredmail-release'

- .github/workflows/ci.yaml
- CONTRIBUTORS.md
- distro.py
- tox.ini
Type checking helps build confidence that an internally consistent API
is used correctly.
Use type comments rather than annotations to retain compatibility with
Python 2.7.
The functools.cached_property is now used on Python 3.8+ as this helps
mypy understand the type of the cached property.
Rationale
---------
The pip project vendors a copy of distro.py:
https://github.com/pypa/pip/blob/20.3.3/src/pip/_vendor/distro.py
pip also uses mypy. Right now, pip must workaround or ignore type errors
that occur from calls to distro.py. By including types directly in the
library, it will help distro, pip, and any other library users running
mypy.
> Add mypy type checking

- README.md
- distro.py
Python 3.8 release has since passed, changed the wording from future
tense to past tense.
> Update comments regarding platform.linux_distribution deprecation

- .github/workflows/ci.yaml
- distro.py
- docs/conf.py
- setup.cfg
- setup.py
- tests/test_distro.py
- tox.ini
Using isort helps make the import order and code style consistent across
files and contributions. Let the tools and CI handle the details to
avoid friction during new contributions and review.
https://pycqa.github.io/isort/
> Introduce isort for consistent formatting of imports

- distro.py
- docs/conf.py
- setup.cfg
- setup.py
Avoid mixing code with configuration.
Running setuptools no longer runs arbitrary custom code, it is all
driven through a key/value configuration file, setup.cfg.
This also simplifies other tools interaction. For example, the Sphinx
config no longer needs to parse source code (and hope the format hasn't
changed). Now, it can use the configparser library to pull values from
setup.cfg.
> Replace setup.py with declarative setup.cfg

- README.md
- docs/conf.py
As platform.linux_distribution() and platform.dist() were removed from
Python 3, the doc links no longer exist. For these deprecated functions,
use Python 3.7, the last version to include them.
> Update platform.linux_distribution links to Python 3.7

- distro.py
- tests/test_distro.py
Users should use distro.id(), distro.version(), and distro.name()
instead.
Refs #263
> Formally deprecate distro.linux_distribution()

- distro.py
- docs/index.rst
In index.rst, the word BSD had a single star. Remove it as the word
doesn't need emphasizing. Fixes warning:
docs/index.rst:23: WARNING: Inline emphasis start-string without end-string.
The section "uname command output" doesn't exist, so remove the link.
Fixes warning:
docs/index.rst:57: WARNING: Unknown target name: "uname command output".
In commit 7d30cf20c418e7af9aad08e9c6277c9c4a699f2b the name was changed
from "ld" to "distro". One mention in the docs was missed. Fixes the
warning:
docs/index.rst:84: WARNING: py:func reference target not found: ld.info
The function distro.uname_info is undocumented. Other docs shouldn't
reference it. Fixes warning:
distro.py:docstring of distro.LinuxDistribution.uname_info:4: WARNING: py:func reference target not found: distro.uname_info
The …
> Fix several warnings when building the docs

- .github/workflows/ci.yaml
- tox.ini
Unify the default testenv and pywin. These two environments don't
require any differences. The previously passed environment variables go
unused.
Only install a minimal set of dependencies required to run the tox
environments. This helps them run a tiny bit faster.
Bump minversion to 1.9 due to using the skip_install configuration
option.
Drop the GitHub actions "toxenv" matrix variable. As tox command is
executed with "-e py", tox will use the default Python which is already
controlled by GHA.
Rename GHA lint to Lint for consistent capitalization.
> Simplify tox and GitHub actions configuration

- CHANGELOG.md
- distro.py
Created a changelog with I believe everything that's landed since last release.
[You can take a peek if I missed anything](https://github.com/python-distro/distro/compare/v1.5.0...master). Put the release date on 2021-07-14 to give time to review but if we need to update the date we can on release day.
Once we merge this I'll create a tag and start the deployment which will also require an approval from someone on the team :)
> Release v1.6.0

- Makefile
Helps catch additional doc errors such as missing references.
Can't yet enable the "turn warnings into errors" option as there remain
a few warnings:
.../distro.py:docstring of distro.info:: WARNING: py:class reference target not found: InfoDict
.../distro.py:docstring of distro.LinuxDistribution.info:: WARNING: py:class reference target not found: InfoDict
> Enable Sphinx "nitpicky" mode

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- README.md
- distro.py
- docs/index.rst
- query_local_distro.py
- setup.cfg
- tests/test_distro.py
- tox.ini
Python 2.7 and 3.4, and 3.5 are end of life. They are no longer
receiving bug fixes, including for security issues. For additional
details on support Python versions, see:
Supported: https://devguide.python.org/#status-of-python-branches
EOL: https://devguide.python.org/devcycle/#end-of-life-branches
Removing support for EOL Pythons will reduce testing and maintenance
resources while allowing the library to move towards a modern Python 3
style.
> Drop support for EOL Pythons

- distro.py
- tests/resources/testdistros/distro/dontincludeuname/bin/uname
- tests/test_distro.py
While working on #264 (leading to #304), I noticed that the `include_uname` parameter is completely being ignored by the code base.
This PR addresses this issue and propose a new test to prevent future regression.
Bye 👋
---
**EDIT** : [A quick GitHub search](https://github.com/search?q=include_uname+-filename%3Adistro.py+language%3APython&type=Code) shows that "no one" (at least on this forge) actually uses this flag.
---
**EDIT 2** : I can backport this patch to the `python2.7-support` branch if you're OK with that.
Closes https://github.com/python-distro/distro/issues/309
> Fix ignored `include_uname` parameter

- distro.py
- tests/resources/testdistros/distro/emptyuname/bin/uname
- tests/test_distro.py
> closes #264
---
**EDIT** : I can backport this patch to the `python2.7-support` branch if you're OK with that.
> Fix crash when `uname -rs` output is empty

- distro.py
This allows executing the file as a standalone script.
Previously, without the shebang, trying to execute results in the
following:
$ ./distro.py
./distro.py: line 28: platform.linux_distribution: command not found
./distro.py: line 28: platform.dist: command not found
./distro.py: line 28: Python: command not found
./distro.py: command substitution: line 29: syntax error near unexpected token `newline'
./distro.py: command substitution: line 29: `<https://bugs.python.org/issue1322>'
...
Now:
$ ./distro.py
Name: Fedora 34 (Workstation Edition)
Version: 34
Codename:
> Add shebang to distro.py

- distro.py
This patch fixes execution when system default locale does not support Unicode.
distro actually didn't honor OS-RELEASE(5), telling us to expect UTF-8 encoded strings : <https://www.freedesktop.org/software/systemd/man/os-release.html#Description>
Against Python 3.10 with `warn_default_encoding` enabled flag, this silences `EncodingWarning`.
Closes #243.
---
EDIT : it looks like Frank does not have write access nor is member of @python-distro/maintainers
> Specifies UTF-8 encoding when opening os-release/distro release files

- src/distro/distro.py
- tests/resources/distros/buildroot/etc/os-release
- tests/test_distro.py
This pull request adds Buildroot Linux in distro.id() documentation list and a test.
See: https://buildroot.org/
> Add Buildroot

- src/distro/distro.py
- tests/resources/distros/guix/etc/os-release
- tests/test_distro.py
Dear maintainers :pray: 
` os-release` file has been copied from : <https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/system.scm?id=245602604455ad9f48571af1fc9ecd6493f6e290#n855>
Closes #303.
Also see #308.
---
CI is currently failing due to an issue with Black and the `click` dependency (not related to this PR), see #331.
Thanks bye :wave:
> Add Guix System

- README.md
Remove `distro.linux_distribution()` since it has been depreciated in the 'Usage' code block and replace it with `distro.name()` and `distro.version()` examples.
Thanks a lot to the creator, maintainers and everyone involved with the project, this library is incredibly useful
> Improve readme 'usage' code block

- src/distro/distro.py
- tests/test_distro.py
This patch is a follow-up for 6d44662 (#333), introducing caching of `/etc/debian_version` file content, to prevent opening and reading operations for each `distro.version()` call.
---
@python-distro/maintainers : we can release a new version once this PR is merged 🙂
> Cache `/etc/debian_version` content

- distro.py
- tests/test_distro.py
Backport of #349 for `python2.7-support` branch.
> [PYTHON 2.7 SUPPORT] Cache `/etc/debian_version` content

- tests/resources/distros/debiantesting/bin/lsb_release
- tests/resources/distros/debiantesting/etc/debian_version
- tests/resources/distros/debiantesting/etc/os-release
- tests/test_distro.py
Debian Testing's version metadata is a different format to the Debian Release version metadata. I hope having this in your test suite will be helpful.
I found that function `version()` in v1.6.0 of `distro` was returning:
```
(Pdb) p versions
['', 'n/a', '', '', '', '']
```
in https://github.com/spack/spack/ v0.19.1. Spack was then taking the first element of "n/a" (i.e. "n") and using it at as the version!
> Add Debian Testing to the tests

- src/distro/distro.py
Dear Sebastian, dear maintainers,
Closes https://github.com/python-distro/distro/issues/358
It was observed that on ubuntu22.04.2 instances created on GCP and Azure with python installed, distro.version() returned incorrect version due to incorrect version present in  /etc/ec2_version file.
This pull request contains a small change to add /etc/ec2_version as part of _DISTRO_RELEASE_IGNORE_BASENAMES, so that it wont be used as data source.
Thank you.
> Ignore the file '/etc/ec2_version'

- src/distro/distro.py
This commit modifies the `distro.info()` method in the `distro.py` file. The method now returns an `InfoDict` object instead of a regular dictionary. This change improves the consistency and readability of the codebase. The `InfoDict` object contains the distribution ID, version, and version parts. The change does not affect the functionality of the method.
> Refactor `distro.info()` method to return an `InfoDict`

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- tox.ini
```diff
strategy:
matrix:
python:
+         - "3.11"
+         - "3.12"
include:
+         - os: "ubuntu-latest"
+           python: "pypy-3.10"
+         - os: "macos-latest"
+           python: 3.x
```
> Test on modern versions of CPython and PyPy and macOS

- src/distro/distro.py
Usually, when `distro` is used in Windows, it returns nothing. Any call to `lsb_release`, `uname`, etc, raises a `[[WinError 2] The system cannot find the file specified` error, which is properly handled. However, in a particular environment where I've run it, I've found that the call to `uname` raises a `CalledProcessError`, because a Policy or a Security Control is injecting a non-zero return code:
```
t=2024-10-04T15:13:39+0200  Command '('uname', '-rs')' returned non-zero exit status 3221225794.
Traceback (most recent call last):
File "C:\...\main.py", line 123, in __check_supported_platform
distro_id = distro.id()
^^^^^^^^^^^
File "C:\...\site-packages\distro\distro.py", line 284, in id
return _distro.id()
^^^^^^^^^^^^
File "C:\...\site-packages\distro\distro.py", line 855, in id …
```
> Handle `CalledProcessError` when calling `uname`
